version: "3.4"
services:
  web:
    build:
      context: ./ 
      target: production
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://db:27017/camel
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
